global:
  scrape_interval: 30s

scrape_configs:
  - job_name: asr_app
    static_configs:
    - targets:
        - asr_app:8000

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']